definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: dataset.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
  ml_methods:
    PWM:
      PWM:
        locus: beta
        sequence_type: amino_acid
        region_type: IMGT_CDR3
    LSTM:
      SimpleLSTM:
        locus: beta
        sequence_type: amino_acid
        num_epochs: 20 #500
        hidden_size: 1024 #64
        learning_rate: 0.001
        batch_size: 100 #0
        embed_size: 256 #100
        temperature: 1 #0.4
        num_layers: 3 #2
        device: cpu
        region_type: IMGT_CDR3
    VAE:
      SimpleVAE:
        batch_size: 100 #0
        beta: 0.75
        cdr3_embed_dim: 21
        locus: beta
        device: cpu
        j_gene_embed_dim: 13
        latent_dim: 30 #20
        linear_nodes_count: 256 #75
        num_epochs: 500
        patience: 20
        pretrains: 5 #10
        v_gene_embed_dim: 30
        warmup_epochs: 20
        validation_split: 0.1


instructions:
  PWM:
    type: TrainGenModel
    export_combined_dataset: True
    dataset: dataset
    method: PWM
    gen_examples_count: 3000
    number_of_processes: 4
  LSTM:
    type: TrainGenModel
    export_combined_dataset: True
    dataset: dataset
    method: LSTM
    gen_examples_count: 3000
    number_of_processes: 4
  VAE:
    type: TrainGenModel
    export_combined_dataset: True
    dataset: dataset
    method: VAE
    gen_examples_count: 3000
    number_of_processes: 4
