definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: generative_air_benchmark/results/00_simulation/full_simulated_dataset.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
  ml_methods:
    PWM:
      PWM:
        locus: beta
        sequence_type: amino_acid
        region_type: IMGT_CDR3
    LSTM:
      SimpleLSTM:
        locus: beta
        sequence_type: amino_acid
        num_epochs: 20
        hidden_size: 1024
        learning_rate: 0.001
        batch_size: 100
        embed_size: 256
        temperature: 1
        num_layers: 3
        device: cpu
        region_type: IMGT_CDR3
    VAE:
      SimpleVAE:
        batch_size: 100
        beta: 0.75
        cdr3_embed_dim: 21
        locus: beta
        device: cpu
        j_gene_embed_dim: 13
        latent_dim: 30
        linear_nodes_count: 256
        num_epochs: 500
        patience: 20
        pretrains: 5
        v_gene_embed_dim: 30
        warmup_epochs: 20
        validation_split: 0.1

instructions:
  gen_models:
    type: TrainGenModel
    export_combined_dataset: True
    dataset: dataset
    methods: [ PWM, VAE, LSTM ]
    gen_examples_count: 1500
    number_of_processes: 1
    split_strategy: MANUAL
    split_config:
      train_metadata_path: generative_air_benchmark/dummy_results/00_simulation/train_ids.csv
      test_metadata_path: generative_air_benchmark/dummy_results/00_simulation/test_ids.csv