definitions:
  datasets:
    PWM_dataset:
      format: AIRR
      params:
        path: generative_air_benchmark/results/01_train/PWM/exported_combined_dataset/combined_PWM_dataset.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
    VAE_dataset:
      format: AIRR
      params:
        path: generative_air_benchmark/results/01_train/VAE/exported_combined_dataset/combined_VAE_dataset.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
    LSTM_dataset:
      format: AIRR
      params:
        path: generative_air_benchmark/results/01_train/LSTM/exported_combined_dataset/combined_LSTM_dataset.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
  encodings:
    3mer_encoding:
      KmerFrequency:
        k: 3
        sequence_type: amino_acid
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    4mer_encoding:
      KmerFrequency:
        k: 4
        sequence_type: amino_acid
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    5mer_encoding:
      KmerFrequency:
        k: 5
        sequence_type: amino_acid
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    gapped_3mer_encoding:
      KmerFrequency:
        sequence_encoding: gapped_kmer
        sequence_type: amino_acid
        k_left: 2
        k_right: 1
        min_gap: 2
        max_gap: 2
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    gapped_4mer_encoding:
      KmerFrequency:
        sequence_encoding: gapped_kmer
        sequence_type: amino_acid
        k_left: 2
        k_right: 2
        min_gap: 1
        max_gap: 1
        scale_to_unit_variance: False
        scale_to_zero_mean: False
  reports:
    feature_value_barplot:
      FeatureValueBarplot:
        color_grouping_label: dataset_split
        plot_all_features: false
        plot_top_n: 25

instructions:
  data_reports:
    type: ExploratoryAnalysis
    number_of_processes: 1
    analyses:
      PWM_3mer_analysis:
        dataset: PWM_dataset
        encoding: 3mer_encoding
        reports: [ feature_value_barplot ]
      PWM_4mer_analysis:
        dataset: PWM_dataset
        encoding: 4mer_encoding
        reports: [ feature_value_barplot ]
      PWM_5mer_analysis:
        dataset: PWM_dataset
        encoding: 5mer_encoding
        reports: [ feature_value_barplot ]
      PWM_gapped_3mer_analysis:
        dataset: PWM_dataset
        encoding: gapped_3mer_encoding
        reports: [ feature_value_barplot ]
      PWM_gapped_4mer_analysis:
        dataset: PWM_dataset
        encoding: gapped_4mer_encoding
        reports: [ feature_value_barplot ]

      VAE_3mer_analysis:
        dataset: VAE_dataset
        encoding: 3mer_encoding
        reports: [ feature_value_barplot ]
      VAE_4mer_analysis:
        dataset: VAE_dataset
        encoding: 4mer_encoding
        reports: [ feature_value_barplot ]
      VAE_5mer_analysis:
        dataset: VAE_dataset
        encoding: 5mer_encoding
        reports: [ feature_value_barplot ]
      VAE_gapped_3mer_analysis:
        dataset: VAE_dataset
        encoding: gapped_3mer_encoding
        reports: [ feature_value_barplot ]
      VAE_gapped_4mer_analysis:
        dataset: VAE_dataset
        encoding: gapped_4mer_encoding
        reports: [ feature_value_barplot ]

      LSTM_3mer_analysis:
        dataset: LSTM_dataset
        encoding: 3mer_encoding
        reports: [ feature_value_barplot ]
      LSTM_4mer_analysis:
        dataset: LSTM_dataset
        encoding: 4mer_encoding
        reports: [ feature_value_barplot ]
      LSTM_5mer_analysis:
        dataset: LSTM_dataset
        encoding: 5mer_encoding
        reports: [ feature_value_barplot ]
      LSTM_gapped_3mer_analysis:
        dataset: LSTM_dataset
        encoding: gapped_3mer_encoding
        reports: [ feature_value_barplot ]
      LSTM_gapped_4mer_analysis:
        dataset: LSTM_dataset
        encoding: gapped_4mer_encoding
        reports: [ feature_value_barplot ]

