definitions:
  datasets:
    PWM_dataset:
      format: AIRR
      params:
        path: generative_air_benchmark/dummy_results/02_filter/data_export/PWM_dataset/AIRR/subset_PWM_dataset_filtered.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
        import_illegal_characters: True
    VAE_dataset:
      format: AIRR
      params:
        path: generative_air_benchmark/dummy_results/02_filter/data_export/VAE_dataset/AIRR/subset_VAE_dataset_filtered.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
        import_illegal_characters: True
    LSTM_dataset:
      format: AIRR
      params:
        path: generative_air_benchmark/dummy_results/02_filter/data_export/LSTM_dataset/AIRR/subset_LSTM_dataset_filtered.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_CDR3
        separator: "\t"
        import_illegal_characters: True
  encodings:
    3mer_encoding:
      KmerFrequency:
        k: 3
        sequence_type: amino_acid
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    4mer_encoding:
      KmerFrequency:
        k: 4
        sequence_type: amino_acid
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    5mer_encoding:
      KmerFrequency:
        k: 5
        sequence_type: amino_acid
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    gapped_3mer_encoding:
      KmerFrequency:
        sequence_encoding: gapped_kmer
        sequence_type: amino_acid
        k_left: 2
        k_right: 1
        min_gap: 2
        max_gap: 2
        scale_to_unit_variance: False
        scale_to_zero_mean: False
    gapped_4mer_encoding:
      KmerFrequency:
        sequence_encoding: gapped_kmer
        sequence_type: amino_acid
        k_left: 2
        k_right: 2
        min_gap: 1
        max_gap: 1
        scale_to_unit_variance: False
        scale_to_zero_mean: False
  reports:
    feature_comparison:
      FeatureComparison:
        comparison_label: dataset_split
        show_error_bar: False
        log_scale: False
        keep_fraction: 0.4
        error_function: sem

instructions:
  data_reports:
    type: ExploratoryAnalysis
    number_of_processes: 1
    analyses:
      PWM_3mer_analysis:
        dataset: PWM_dataset
        encoding: 3mer_encoding
        reports: [ feature_comparison ]
      PWM_4mer_analysis:
        dataset: PWM_dataset
        encoding: 4mer_encoding
        reports: [ feature_comparison ]
      PWM_5mer_analysis:
        dataset: PWM_dataset
        encoding: 5mer_encoding
        reports: [ feature_comparison ]
      PWM_gapped_3mer_analysis:
        dataset: PWM_dataset
        encoding: gapped_3mer_encoding
        reports: [ feature_comparison ]
      PWM_gapped_4mer_analysis:
        dataset: PWM_dataset
        encoding: gapped_4mer_encoding
        reports: [ feature_comparison ]

      VAE_3mer_analysis:
        dataset: VAE_dataset
        encoding: 3mer_encoding
        reports: [ feature_comparison ]
      VAE_4mer_analysis:
        dataset: VAE_dataset
        encoding: 4mer_encoding
        reports: [ feature_comparison ]
      VAE_5mer_analysis:
        dataset: VAE_dataset
        encoding: 5mer_encoding
        reports: [ feature_comparison ]
      VAE_gapped_3mer_analysis:
        dataset: VAE_dataset
        encoding: gapped_3mer_encoding
        reports: [ feature_comparison ]
      VAE_gapped_4mer_analysis:
        dataset: VAE_dataset
        encoding: gapped_4mer_encoding
        reports: [ feature_comparison ]

      LSTM_3mer_analysis:
        dataset: LSTM_dataset
        encoding: 3mer_encoding
        reports: [ feature_comparison ]
      LSTM_4mer_analysis:
        dataset: LSTM_dataset
        encoding: 4mer_encoding
        reports: [ feature_comparison ]
      LSTM_5mer_analysis:
        dataset: LSTM_dataset
        encoding: 5mer_encoding
        reports: [ feature_comparison ]
      LSTM_gapped_3mer_analysis:
        dataset: LSTM_dataset
        encoding: gapped_3mer_encoding
        reports: [ feature_comparison ]
      LSTM_gapped_4mer_analysis:
        dataset: LSTM_dataset
        encoding: gapped_4mer_encoding
        reports: [ feature_comparison ]


